### ISSUE TITLE
publish chirp on npm

### ISSUE THREAD

**Issue by ianhobbs** [Chirp-SEO/chirp-seo#2]
I use npm a lot of things and pre-build perch pages with pug and kit.
While I realize that npm is not conventionally used for PHP.
I'd like to see it there.

This may be extra work for you.
https://docs.npmjs.com/getting-started

Thanks Ian

**Comment by husseinalhammad** [comment]
NPM is a package manager for JS. It helps you manage your JS dependencies.

I think it would make more sense to publish a PHP package on [Packagist](https://packagist.org/) so it is installable with [Composer](https://getcomposer.org/).

**Comment by ryangittings** [comment]
Great suggestion! I think with Perch's current install method, most people will be installing manually as they do other apps. 

Should Perch 4 change the installation method or rely on composer; then I'm more than happy to add this. Completely in agreement with @husseinalhammad that composer is more relevant here!

**Comment by ryangittings** [comment]
Will close for now, but keep a close eye on what v4 brings!
